name: Build and Deploy Frontend
on:
  workflow_dispatch:
    
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-central1-c


jobs:
  deploy-frontend-on-qa:
    env:
      GKE_CLUSTER: gke-qa-prod
    name: deploy frontend on QA
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Cache Packages
      uses: actions/cache@v2
      with:
        path: |
          ui/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.TESTFILE_SVC }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
          # Configure Docker to use the gcloud command-line tool as a credential
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Prepare Docker
      run: |
        echo "==========Docker Login=========="
        echo ${{ secrets.TOKEN }} | docker login docker.pkg.github.com -u piyushknoldus --password-stdin
        docker pull docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui_qa:latest
        docker tag docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui_qa:latest docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui_qa-archived:latest
    # Build the Docker image
    - name: Package Frontend
      working-directory: ui
      run: |
        sed -i 's/ENVIRONMENT/qa/g' Dockerfile
        docker build -t docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui_qa:latest .
    # Publish the Docker image to Github Packages
    - name: Publish Docker Image to Github Packages
      run: |
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui_qa:latest
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui_qa-archived:latest
    # Deploy Leaderboard to GKE
    - name: Deploy to GKE
      run: |-
        kubectl scale deployment frontend --replicas 0 -n leaderboard
        sleep 30
        kubectl scale deployment frontend --replicas 1 -n leaderboard
        
          deploy-frontend-on-prod:
    env:
      GKE_CLUSTER: allknols
    name: deploy on frontend production
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Cache Packages
      uses: actions/cache@v2
      with:
        path: |
          ui/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.TESTFILE_SVC }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    # Configure Docker to use the gcloud command-line tool as a credential
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Prepare Docker
      run: |
        echo "==========Docker Login=========="
        echo ${{ secrets.TOKEN }} | docker login docker.pkg.github.com -u piyushknoldus --password-stdin
        docker pull docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui:latest
        docker tag docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui:latest docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui-archived:latest
    # Build the Docker image
    - name: Package Frontend
      working-directory: ui
      run: |
        sed -i 's/ENVIRONMENT/prod/g' Dockerfile
        docker build -t docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui:latest .
    # Publish the Docker image to Github Packages
    - name: Publish Dcoker Image to Github Packages
      run: |
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui:latest
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard_ui-archived:latest
    # Deploy Leaderboard to GKE
    - name: Deploy to GKE
      run: |-
        kubectl scale deployment frontend --replicas 0 -n leaderboard
        sleep 30
        kubectl scale deployment frontend --replicas 1 -n leaderboard
      
  
      
