# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: test
      run: mvn package
      if: steps.extract_branch.outputs.branch == 'Dev'
    - name: Build docker image 
      working-directory: .
      run: |
            docker build -t  ghcr.io/kirtighugtyal6/testfile/springapp:latest .
      
    - name: Package Frontend
      run: |
        docker build -t test-image .
        
    - uses: anchore/sbom-action@v0
      with: 
        image: test-image:latest
        format: cyclonedx
        artifact-name: report.cyclonedx
        output-file: ./report.cyclonedx
        
    - name: cat report
      run: |
        cat report.cyclonedx
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./
        syft test-image:latest
        syft test-image:latest --scope all-layers
        
#     - name: Send mail
#       uses: kirti/action-send-mail@v3
#       with:
#     # Required mail server address:
#         server_address: smtp.gmail.com
#      # Required mail server port:
#         server_port: 465
#     # Optional (recommended): mail server username:
#         username: ${{secrets.MAIL_USERNAME}}
#     # Optional (recommended) mail server password:
#         password: ${{secrets.MAIL_PASSWORD}}
#     # Required mail subject:
#         subject: Github Actions job result
#     # Required recipients' addresses:
#         to: keetyal@gmail.com
#     # Required sender full name (address can be skipped):
#         from: Kirti Ghugtyal # <user@example.com>
#     # Optional whether this connection use TLS (default is true if server_port is 465)
#         secure: true
    
    - name: dockertoken
      run: |
        echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u kirtighugtyal6 --password-stdin
    
    - name: publish docker image
      run: |
        docker push  ghcr.io/kirtighugtyal6/testfile/springapp:latest

    - name: commmand check
      run: echo ${{github.event.inputs.deploy == 'backend' || github.event.inputs.deploy == 'both'  && github.ref == 'refs/heads/main'}}
    - name: print
      run: echo 'both'



      
